version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: bd
    ports:
      - "3306:3306"
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    restart: unless-stopped

  apache-php:
    build: .
    container_name: apache-php
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
    restart: unless-stopped
